install.packages("ggrepel", repos = "http://cran.rstudio.com")
devtools::install_github("thomasp85/patchwork")
install.packages("sf", repos = "http://cran.rstudio.com")
install.packages("rnaturalearth", repos = "http://cran.rstudio.com")
install.packages("rnaturalearthdata", repos = "http://cran.rstudio.com")
